### ISSUE TITLE
Paired-end read support

### ISSUE THREAD

**Issue by mictadlo** [GATB/bloocoo#1]
Hi, 
Any plans to implement paired-end read support? Have you ever tried  [Flash](http://scottmyourstone.blogspot.com.au/2013/10/merging-overlapping-paired-end-reads.html) or
shuffleReadsfasta.pl from Velvet?

Thank you in advance.

Mic

**Comment by rizkg** [comment]
Hi, I am not sure what you mean, how would you like an error-correction tool like bloocoo to take paired-end reads into account ? Do you mean if paired reads overlap ?

**Comment by mictadlo** [comment]
Hi, I thought that other {error tools] (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0509-9) support paired-end data and it might be possible to it with bloocoo, too? I have paired-end data i.e. it means I could use the with bloocoo?

**Comment by rizkg** [comment]
Yes, the input of bloocoo can be paired-end reads. Just give the list of read files separated by commas, like this :
 `Bloocoo -file reads1.fastq,reads2.fastq`

**Comment by mictadlo** [comment]
Thank you
